### ISSUE TITLE
Wave XLR WIN10 left side only output

### ISSUE THREAD

**Issue by oscla** [werman/noise-suppression-for-voice#100]
I like what the VST is doing and how it is working, but perhaps I am not as technical for this and I do not understand how to get it to output in stereo for the stream. When I monitor it in Wave XLR or "listen" to the Stream output in Wave XLR it is in stereo, but when I record or send it forward it only plays from the left side.

Is there a way to enable stereo on WIN10?

**Comment by ip75** [comment]
i have the same issue. Unable to use vst plugin but one channel cleared very carefully from noise.

**Comment by werman** [comment]
VST plugin is mono at the moment.

Wave XLR is a microphone right? Are you using Equalizer APO to load the plugin? If you are using Equalizer APO I think you could assign the plugin for each channel independently.

**Comment by oscla** [comment]
Elgato Wave XLR is a USB interface that also acts as a VST host with their latest software version and it is a very good software for streaming, but it does not do channel separation.

**Comment by AITYunivers** [comment]
I'd honestly rather the VST itself turn stereo than use Equalizer APO because the program breaks 90% of the time for me and it's honestly much too annoying.

**Comment by oscla** [comment]
Update from me, since I swapped out my SSD for a bigger one and completely reinstalled Windows, the VST is working in stereo when using the Elgato Wave XLR.

**Comment by werman** [comment]
Released v1.01, now there is stereo version in binaries.
