### ISSUE TITLE
OBS Won't open the Plugin Interface

### ISSUE THREAD

**Issue by eriksonssilva** [werman/noise-suppression-for-voice#105]
Hello @werman ! Thanks a lot for this awesome plugin!
I was really excited when I tested it on Reaper and it worked amazingly well!
However, as the title says, OBS does see it but it won't open the interface for some reason...
I made sure to download the correct version (x64), and since it works on Reaper, I think the fault does not belong to the VST necessarily.
However on issue #56 , you compiled a stereo version and its interface can be opened in OBS...
Can you please enlighten me?
Thanks a lot!

**Comment by werman** [comment]
Which system do you have and how do you load vst plugin in OBS? I have Linux and I don't see my vst plugin in the list after I followed instructions from https://obsproject.com/forum/threads/vst-in-obs-for-linux.123735/

However I think OBS has built-in rnnoise noise suppression which is the same my plugin uses, so you probably should use it:
![image](https://user-images.githubusercontent.com/3993671/150678776-157920f8-a7c9-4a62-bb2e-51577eb22e56.png)

**Comment by eriksonssilva** [comment]
My system is Win 10 64 bits, and I load it the normal way (filters > VST2). The only thing is that it doesn't show up as Noise Suppression. Instead it shows up as libnoise. But it does work!

Although the OBS built in Kinda works, It seems to let more noises through, plus I can't adjust the threshold.
Also it is MUCH more CPU hungry than yours.

I was able compiling the VST and change its parameters. However, for some reason I can't find  a way of compiling the 64x version, and therefore OBS will open it, but will "ignore" the plugin...
I'll keep trying!
Thanks a lot!

**Comment by werman** [comment]
> Although the OBS built in Kinda works, It seems to let more noises through, plus I can't adjust the threshold.
Also it is MUCH more CPU hungry than yours.

Interesting...

> However, for some reason I can't find a way of compiling the 64x version, and therefore OBS will open it, but will "ignore" the plugin...

Why do you think that what you compiled is not x64? By default x64 would be compiled.

Also, could you add a screenshot of the interface in OBS you mention?

Anyway, back to the original issue, maybe OBS doesn't use 1 channel plugins for 2 channel input, so both plugin and OBS work correctly. So that's another reason for me to add 2 channel version.

**Comment by eriksonssilva** [comment]
Here's the name:
![image](https://user-images.githubusercontent.com/43449566/150696756-b6a4fa75-5b83-42d7-84bf-862700eb519a.png)

And here the "Interface":

![image](https://user-images.githubusercontent.com/43449566/150696772-ed7a873f-9567-407f-882e-c465e8de9a41.png)

> Why do you think that what you compiled is not x64? By default x64 would be compiled.

I am on windows 10, so I had to use MINGW.
The problem is that, when I do "make", it says that this command is not valid.
I have to them use mingw32-make, and then it compiles.
But it compiles the 32bit plugin.
I did not know it was 32 bits, until I changed the plugin to have 2 ins - 2 outs, and then Reaper shows "Noise Suppression (x86)".
I know it's on my end, but I did not have time trying to fix it yet.

**Comment by eriksonssilva** [comment]
Ok, I was able compiling the 64 version.
But since it's "naturally" mono, no matter what I do on OBS, it won't work stereo.
I was so happy that I could compile it with the filter the way I wanted, but soon I wasn't happy anymore.
I have used all the programming knowledge I have (little to none), ye I couldn't make it work as stereo.
Here's a "version" of the code that works but with robotic voice:

`RnNoiseVstPlugin::RnNoiseVstPlugin(audioMasterCallback audioMaster, VstInt32 numPrograms, VstInt32 numParams)
        : AudioEffectX(audioMaster, numPrograms, numParams) {
    setNumInputs(2); // mono in
    setNumOutputs(2); // mono out
    setUniqueID(366056);
    canProcessReplacing(); // supports replacing mode

    m_rnNoisePlugin = std::make_unique<RnNoiseCommonPlugin>();
}

RnNoiseVstPlugin::~RnNoiseVstPlugin() = default;

void RnNoiseVstPlugin::processReplacing(float **inputs, float **outputs, VstInt32 sampleFrames) {
    // Mono in/out only
    float *inChannel0[2] = {inputs[0], inputs[1]};
    float *outChannel0[2] = {outputs[0], outputs[1]}; 


    for (size_t i = 0; i < 2; i++)
    {
        m_rnNoisePlugin->process(inChannel0[i], outChannel0[i], sampleFrames, paramVadThreshold);
    }
    
    
}
`

Could you shed some light on me?
Thanks a lot!

**Comment by werman** [comment]
Released v1.01, we now have GUI and stereo version.
