### ISSUE TITLE
Usage under Windows APO Equalizer

### ISSUE THREAD

**Issue by x3oo** [werman/noise-suppression-for-voice#107]
For some reason Apo equalizer isnt able to show any settings, so you cant set vod levels.
but there is a ladspa plugin included for windows and a lv2 plugin.
is there another way to integrate those plugins into win10?

**Comment by werman** [comment]
You could edit VST settings in Equalizer APO, see https://github.com/werman/noise-suppression-for-voice/issues/44#issuecomment-701439584

There the value is from 0.0 to 1.0, probably you could just divide VAD level by 100 and enter it there.

**Comment by MildlyInterested** [comment]
Had the same issue and switched to [VSTHost](https://www.hermannseib.com/english/vsthost.htm).
Not as neat and requires you do some some audio routing via voicemeter or virtual audio cable but it works. 

To start vshost on login I copied a shortcut to `vsthost.exe` to my `C:\Users\USER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` folder. Save your "Performance" in VSTHost and tick the "reload" button and it'll bring back your latest config on boot up. Plugin setting won't save tho (and not sure if they do anything...).

**Comment by werman** [comment]
Released v1.01, now there is GUI to change params.
