### ISSUE TITLE
Plugin does not work on higher sample rates

### ISSUE THREAD

**Issue by ndunnett** [werman/noise-suppression-for-voice#110]
I've just tried using the compiled VST plugin with Equalizer APO, and while it works fine on 44.1 kHz and 48 kHz, if I use 96 kHz or 192 kHz the plugin blocks everything including my voice.

**Comment by theglobe** [comment]
The plugin is trained for 48 kHz only. Even though it works at 44.1 kHz, it is not optimized for that and at 96 kHz it interprets your voice as something outside the desirable frequency range and thus blocks it.

**Comment by werman** [comment]
Added a stern warning to use only 48 kHz
