### ISSUE TITLE
Make 200ms VAD grace period variable

### ISSUE THREAD

**Issue by fquirin** [werman/noise-suppression-for-voice#112]
First of all let me say how awesome this plugin is! :star2: 
I've been experimenting with it on Raspberry Pi 4 for [SEPIA Open Assistant](https://sepia-framework.github.io/) using Pulseaudio and I'm getting great results with acceptable CPU load (about 40% on one core).

The problem I'm experiencing though is that wake-word recognition gets worse and I think this is because of the aggressive VAD filtering leading to a few missing samples at the beginning of the wake-word. Using something like "Hey hey SEPIA" instead of "Hey SEPIA" for example seems to be a partial "workaround".

Is it possible to make the VAD grace period (`k_vadGracePeriodSamples` I believe) variable and maybe introduce some parameter to keep a few more frames at the onset? Latency is not a big problem for the input so maybe one could buffer a few frames (50ms ?!)

**Comment by werman** [comment]
Released v1.01, grace period is configurable now.
