### ISSUE TITLE
Consider updating the release package

### ISSUE THREAD

**Issue by markski1** [werman/noise-suppression-for-voice#115]
Hello, I'm not sure if an issue is the right place for this, but I'd like to suggest updating the Release package with a build of the current code. I see pull requests made after the [date of the last release](https://github.com/werman/noise-suppression-for-voice/releases/tag/v0.91) which seem to fix latency and crackling issues, and I think these should be made available to users of this plugin who can't/don't know how to build it from source.

Cheers

**Comment by torecagli** [comment]
Can anyone point to a guide showing how to compile a VST with the latest version? I have zero knowledge about compiling or programming.

**Comment by werman** [comment]
Released v1.01
