### ISSUE TITLE
Stereo version?

### ISSUE THREAD

**Issue by Hinge45** [werman/noise-suppression-for-voice#118]
sorry kinda dumb here, is there a stereo version for light host? or at least a stereo upmix version?

**Comment by theglobe** [comment]
See https://github.com/werman/noise-suppression-for-voice/pull/5

**Comment by Hinge45** [comment]
ok, thanks for the info, ill just use another plugin to upmix it, but it would be nice if there's an option to downmix and upmix the channel to stereo.

**Comment by werman** [comment]
Release v1.01 with stereo support (or even more for plugins with configurable number of channels).

**Comment by Hinge45** [comment]
ayo tysm
