### ISSUE TITLE
Question/Suggestion: build 32bit vst for windows

### ISSUE THREAD

**Issue by Haruki1** [werman/noise-suppression-for-voice#12]
Im not sure if it is possible now but could I use smth like 32bit version of mingw to build 32bit vst version for windows? im running some other 32 bit plugins on plugin host and i cant use 64 bit vst on that as it is crashes the app.

**Comment by werman** [comment]
You should be able to build it with mingw and MSYS:
```
cmake -D CMAKE_CXX_FLAGS=-m32 -D CMAKE_C_FLAGS=-m32 -Bbuild-x32 -H. -DCMAKE_BUILD_TYPE=Release
cd build-x32
make
```
If something goes wrong I'd try to help.

**Comment by Haruki1** [comment]
im sorry im stupid, was not working all that much with c++ recently. i got myself a mingw-w32 and msys2 and i donwloaded vst sdk.
i run cmake and it generates build-x32 folder with its stuff and then when i try to run make from msys2 terminal i get bash: command make not found. i assume i need to download some packages but i only used apt-get and pacman before and i dont know how to get them.

**Comment by werman** [comment]
See https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2, I think you need to run:
```
pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-i686-cmake
```
or maybe just `pacman -S make`
