### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by Gubba-Monster** [werman/noise-suppression-for-voice#121]
Are there any plans for a GUI version or plugin so that I can change the sensitivity of the suppression, filter etc?

**Comment by werman** [comment]
No, there won't be any GUI, only way to change the parameters is if plugin host provides GUI for the parameters we specify.

**Comment by maosante** [comment]
By the way, I've just design a fancy GUI. Don't really know if is easy to implement and I also changed some therms to accomplish a standard language on most audio plugins. The name of the plugin is up to you of course, this is just an example.

![RNNoise GUI](https://user-images.githubusercontent.com/95062236/175843312-e8d937a8-4b1a-4ab0-8e12-9aa3e87012c6.jpg)

**Comment by Gubba-Monster** [comment]
That's a really nice and clean GUI. I'd really suggest you'd add a compressor to it, it's a very common choice for streamers just to keep a clean sound.

**Comment by Gubba-Monster** [comment]
Another suggestion I have for you is to be able to select what input source it uses, currently I have mine configured to my MV7 but I had to play around to get that working.

**Comment by werman** [comment]
> Hey! I've just design a fancy GUI. Don't really know if is easy to implement. I also changed some therms to accomplish the standard language of most audio plugins. The name of the plugin is up to you of course, this is just an example. Hope you you like it and find it accurate for its functionality.

That's a bit too fancy =) I'm aiming for simplicity and readability. I'm not a user of any other audio plugin so I may not know the trends in gui there.

**Comment by maosante** [comment]
> > Hey! I've just design a fancy GUI. Don't really know if is easy to implement. I also changed some therms to accomplish the standard language of most audio plugins. The name of the plugin is up to you of course, this is just an example. Hope you you like it and find it accurate for its functionality.
> 
> That's a bit too fancy =) I'm aiming for simplicity and readability. I'm not a user of any other audio plugin so I may not know the trends in gui there.

Ok, let me know if it works how its shown above. I can send the files in PNG separated, background, texts and individual knobs in order to be implemented in the plugin. I don't know much either the trends, its just how I think the plugin would benefit graphically for its functionality. Yet it's to be discussed. I'm open to any suggestions.

**Comment by werman** [comment]
What I meant, is that this design doesn't match to how I envision the GUI. To give a concrete feedback:
- White text on a light background isn't good for readability;
- The circle sliders are... , let's say, I'm not a fan of them, but also as far as I understand it's somewhat customary for audio plugins.

Anyway, at the moment I'm not looking for a fancier GUI than I have now. Though thanks for an attempt!

**Comment by werman** [comment]
Release v1.01 with GUI.

**Comment by adamnejm** [comment]
Sorry, but I'm losing my mind... how do I start the GUI application exactly? I'm using the package from official Arch Linux repositories.  
Doesn't look like there are any new files in directories from my $PATH, I don't see any new .desktop files either.

**Comment by werman** [comment]
@adamnejm There is no application with GUI here. There is only GUI for plugins (which are just shared libs), that host application could open (e.g. Carla or Audacity).
