### ISSUE TITLE
No sources are created

### ISSUE THREAD

**Issue by IceDBorn** [werman/noise-suppression-for-voice#122]
I followed the exact instructions in the README and I could not make this to work.

No extra input sources are created.

I'm on Arch, I tried using the AUR package and I even downloaded the plugin for github releases, neither seem to work.

**Comment by werman** [comment]
Are you using pipewire or pulseaudio? Could you post the configs you made?

**Comment by IceDBorn** [comment]
Nevermind, something I installed replaced pipewire-pulse with pulseaudio and pulseadio-bluetooth. Thanks for your time!
