### ISSUE TITLE
No install target for JUCE plugins

### ISSUE THREAD

**Issue by antonio-rojas** [werman/noise-suppression-for-voice#125]
There is no code to install the compiled plugins in
https://github.com/werman/noise-suppression-for-voice/blob/v1.0/src/juce_plugin/CMakeLists.txt

so the plugins are compiled but `cmake --install` does not install them.

**Comment by werman** [comment]
Hmmm, I use `JUCE_COPY_PLUGIN_AFTER_BUILD` to get plugins into folders I want after a build, however it seems I have to do what `JUCE_COPY_PLUGIN_AFTER_BUILD` originally does but for install.

**Comment by antonio-rojas** [comment]
Seems ok after 97560e9ad720e34079ff765c927788e130cdb400
