### ISSUE TITLE
GUI breaks in EqualizerAPO

### ISSUE THREAD

**Issue by pannal** [werman/noise-suppression-for-voice#127]
When moving the mouse over the controls in the new GUI (thanks btw!), the controls themselves glitch out:

![image](https://user-images.githubusercontent.com/1359593/180607663-10104df3-51d0-4269-9d7e-6cb5474f29bf.png)

EqualizerAPO 1.2.1, latest rnnoise.

**Comment by werman** [comment]
Ok, so nothing changed with JUCE update. I cannot reproduce this in virtual machine, maybe when hardware acceleration is enabled some thing goes differently... So much for cross-platform frameworks.

Anyway, does it stays that way forever? Or goes away when moving the window?

**Comment by werman** [comment]
Hmmm, actually I could reproduce this in EqualizerAPO on Windows running in VM. The previous report of this issue was in another host where I wasn't able to reproduce it.

**Comment by werman** [comment]
![image](https://user-images.githubusercontent.com/3993671/180609485-6710f8e0-10c5-4707-96ae-3531d9e038ef.png)

Maybe EqualizerAPO doesn't send events to repaint the window...
