### ISSUE TITLE
Default VAD threshold and README

### ISSUE THREAD

**Issue by pannal** [werman/noise-suppression-for-voice#128]
Hey,

The default VAD threshold was 0.60 for me. The README states that anything between 0.85 and 0.95 should be sufficient.

Shouldn't the default be 0.85 then?

Thanks!

**Comment by werman** [comment]
I thought to err on the safe side. This parameter is meant to be tweaked, and I don't have means to find out a more sensible default.

**Comment by pannal** [comment]
OK, thanks!
