### ISSUE TITLE
VST2 dll 1.01 crash on EqualizerAPO 1.3

### ISSUE THREAD

**Issue by goldie-lin** [werman/noise-suppression-for-voice#129]
When switching VST2 dll from 0.91 to 1.01 in EqualizerAPO,
It will cause EqualizerAPO crash during open dll or turn VST plugin on/off on EqualizerAPO Configuration Editor panel.

https://user-images.githubusercontent.com/731064/180611168-e1f8e3eb-d9e5-4f70-82a7-8849eaac2a39.mp4

Latest Win10 21H2, latest EqualizerAPO 1.3, latest rnnoise_mono.dll 1.01
rnnoise_stereo.dll would crash, too.

Even it didn't crash, 1.01 dll won't has the expected noise reduction effect.
So, I switched back to 0.91

**Comment by goldie-lin** [comment]
My EqualizerAPO config files.
[config.txt](https://github.com/werman/noise-suppression-for-voice/files/9174049/config.txt)
[mic_noise_removal-rnnoise.txt](https://github.com/werman/noise-suppression-for-voice/files/9174047/mic_noise_removal-rnnoise.txt)
[mic_mono2stereo.txt](https://github.com/werman/noise-suppression-for-voice/files/9174050/mic_mono2stereo.txt)

**Comment by werman** [comment]
Thanks for reporting, I could reproduce it. It seems Windows build is cursed... And I have to debug it.

**Comment by goldie-lin** [comment]
Thanks for quickly working on it, I can confirm that 1.02 fixed.
