### ISSUE TITLE
Vst mono interface visual bug

### ISSUE THREAD

**Issue by maosante** [werman/noise-suppression-for-voice#130]
Hi I've tested the vst in Ableton Live on Mac OS, when moving the knobs they overlap and data becomes unreadable, by the other hand 96.000 sampling rate in not supported. The rest seems to be ok, audio is pristine! Thanks for the updated version.

**Comment by werman** [comment]
Are you using the latest 1.02 release (https://github.com/werman/noise-suppression-for-voice/releases/tag/v1.02)? The corruption was originally reported and Windows and I fixed it in this release.
