### ISSUE TITLE
Words starting with "S" are being cut

### ISSUE THREAD

**Issue by azisaka** [werman/noise-suppression-for-voice#134]
I'm a pt-br speaker (not sure if it's relevant). And words starting with the "S" sound get a cut when they start the phrase. Words like "SIM" (yes) and "CERTO" (right, sure) become "IM" and "ERTO".

Even in english, the word "sure" gets a quick cut on the "S" (maybe my pronunciation is not correct?). 

I was wondering if there is a way to work it out, to reduce the "deesser" a little.

**Comment by werman** [comment]
Try increasing `Retroactive VAD Grace Period (ms)` param if it is zero, maybe to 30 or 40 ms

**Comment by azisaka** [comment]
Right way!

**Comment by azisaka** [comment]
Thanks for the help! It gets perfect with 130ms. Is it too much? On the README you say it may introduce latency, but I guess I will have to live with it.

**Comment by werman** [comment]
That's could be too much since it adds 130ms latency, it may be better to just reduce VAD threshold.

Of course it depends on your use-case.

**Comment by azisaka** [comment]
Ended up with

```
"VAD Threshold (%)" 40.0                                                                                                                              
"VAD Grace Period (ms)" 100                                                                                                                           
"Retroactive VAD Grace (ms)" 40                                                                                                                       
```
All fixed. Thanks for the quick answers!
