### ISSUE TITLE
Vst3 crashes wave link

### ISSUE THREAD

**Issue by Gluubb** [werman/noise-suppression-for-voice#146]
I put the rn-noise "vst" stero file into my VST folder and when I scan in wavelink it crashes the program and will not load the vst because it is "broken" according to wavelink. What is the fix for this?

**Comment by werman** [comment]
Which operation system do you have? 

There are already reports that it doesn't work in Elgato Wavelink on macOS, see https://github.com/werman/noise-suppression-for-voice/issues/136. How to fix, don't know, I don't have macOS and I don't have the required mic for this app to work. 

So unless someone debugs the issue, I cannot do anything.

**Comment by Gluubb** [comment]
Windows 11, sorry forgot to post that. If it doesn't work on el gato that sucks but I will use the older version that did/does work. Ok no worries, thank you anyway.
