### ISSUE TITLE
Need Help With Building

### ISSUE THREAD

**Issue by burningtreegames** [werman/noise-suppression-for-voice#153]
I hate to be that guy but this is a bit over my head. I tried the command line x64 install on windows with powershell and it isnt working having an issue with ninja. I tried the cmake gui and works fine. Then I assume I need to open the project in visual studio, I run the solution in release for build all and I get a few errors all similar to this one.

cannot open file 'rnnoise_juce_plugin_stereo_artefacts\Release\rnnoise_stereo_SharedCode.lib'	rnnoise_juce_plugin_stereo_VST	C:\Users\"user"\Desktop\nnns\src\juce_plugin\

I'd really like to use this and have been trying for hours with no luck. Any help pointing me in the right direction would be appreciated.

**Comment by werman** [comment]
The easiest way to build should be:

```
cmake -Bbuild-rel -DCMAKE_BUILD_TYPE=Release --config Release
cmake --build build-rel --parallel
```

**Comment by burningtreegames** [comment]
I wasnt able to get it to work with the --config release but tried it without it and it all worked fine. Thank you very much!
