### ISSUE TITLE
RNNoise Interferes With Music Played On PC

### ISSUE THREAD

**Issue by vonrotten** [werman/noise-suppression-for-voice#159]
When I try to play music on Spotify or Youtube, RNNoise will make the music cut in and out as if it's trying to suppress the music as the plugin thinks it's background noise. This isn't proper behavior, so I would like a new update to the plugin asap please so I can listen to music with the plugin running. This is primarily wanted by me so when I play games on my pc, RNNoise won't cause the in-game music to cut in and out.

**Comment by werman** [comment]
Hi, this is expected behavior, music is kind of a noise and I'm not aware of any denoiser that doesn't behave like that. Anyway, I'm not able to change how denoiser works.

**Comment by ronaldocpontes** [comment]
Just route your game music so it doesn't go through RNNNoise. I use the same technique to add some white 'Vinyl' noise back to zoom calls so people don't feel I have left the call due to silence when I am not speaking.

![image](https://user-images.githubusercontent.com/3316428/210137174-d511fc38-722e-4548-b5b6-23892b22e1be.png)

**Comment by werman** [comment]
@ronaldocpontes that's a good idea

**Comment by vonrotten** [comment]
@ronaldocpontes How would I route my game music or Spotify so it doesn't go through RNNoise. I use Equalizer APO to run RNNoise, and I have no idea how to reroute stuff. So if you could tell me how to do it or how to do it on a different program that isn't Equalizer APO, then I'll appreciate the help greatly.

**Comment by ronaldocpontes** [comment]
I use https://kushview.net/element as a VST host for routing together with https://vb-audio.com/Cable/index.htm on Mac. You can easily find lots of tutorials on youtube on how to use them. Basically, you need to set the game sound output to VBCable and from VBCable and then route both the Mic and VBCable into your speakers using Element or something similar for windows.
```
MIC -> RNNOIUSE ->
                                                SPEAKERS
GAME -> VBCABLE -> 
```

**Comment by vonrotten** [comment]
@ronaldocpontes I've been trying to figure out how to set up element for the past week and a half and I can't figure it out even with tutorials. I'm gonna need some help with this.
