### ISSUE TITLE
error: "Unsupported platform"   #error "Unsupported platform"

### ISSUE THREAD

**Issue by yurivict** [werman/noise-suppression-for-voice#163]
We have the juce-7.0.3 package that works fine on FreeBSD.

Is there any way to use it?

Version: 1.03
FreeBSD 13.1

**Comment by werman** [comment]
Could you test the `develop` branch: https://github.com/werman/noise-suppression-for-voice/tree/develop ? It has `USE_SYSTEM_JUCE` option (so you have to add `-D USE_SYSTEM_JUCE=1` when configuring build dir). If it works I'll move the changes into the main branch.

P.S. Don't create duplicate issues:

![image](https://user-images.githubusercontent.com/3993671/214280935-3d5570a6-da7d-434a-976f-e63b9ad364af.png)
