### ISSUE TITLE
Problem with building plugin

### ISSUE THREAD

**Issue by Aktzin03** [werman/noise-suppression-for-voice#17]
Beginner to this sort of stuff here. I downloaded what I think to be the requirements of this plugin: cmake, MinGW, and the VST SDK's (had to find an older version of vst2, Steinberg website doesn't give the vst2 plugin interface folder). I was able to build the folder, but I ran into a problem with using the "make" command. To be clear, I used "mingw32-make," not sure if that would help, but it's something. Anyway, this is where the process started screwing up:

Scanning dependencies of target rnnoise_vst
[ 52%] Building CXX object src/vst_plugin/CMakeFiles/rnnoise_vst.dir/vst2.x/vstplugmain.cpp.obj
<command-line>:0:0: warning: "__cdecl" redefined
<built-in>: note: this is the location of the previous definition
[ 57%] Building CXX object src/vst_plugin/CMakeFiles/rnnoise_vst.dir/vst2.x/audioeffect.cpp.obj
<command-line>:0:0: warning: "__cdecl" redefined
<built-in>: note: this is the location of the previous definition
C:\Users\lcgra\Desktop\rnnoise vst\src\vst_plugin\vst2.x\audioeffect.cpp: In member function 'virtual void AudioEffect::int2string(VstInt32, char*, VstInt32)':
C:\Users\lcgra\Desktop\rnnoise vst\src\vst_plugin\vst2.x\audioeffect.cpp:530:24: warning: narrowing conversion of '(48 + ((int)((char)digit)))' from 'int' to 'char' inside { } [-Wnarrowing]
    char temp[2] = {'0' + (char)digit, '\0'};
                    ~~~~^~~~~~~~~~~~~
[ 63%] Building CXX object src/vst_plugin/CMakeFiles/rnnoise_vst.dir/vst2.x/audioeffectx.cpp.obj
<command-line>:0:0: warning: "__cdecl" redefined
<built-in>: note: this is the location of the previous definition
C:\Users\lcgra\Desktop\rnnoise vst\src\vst_plugin\vst2.x\audioeffectx.cpp: In member function 'virtual void AudioEffectX::resume()':
C:\Users\lcgra\Desktop\rnnoise vst\src\vst_plugin\vst2.x\audioeffectx.cpp:307:69: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  if (cEffect.flags & effFlagsIsSynth || canDo ("receiveVstMidiEvent") == 1)
                                                                     ^
[ 68%] Building CXX object src/vst_plugin/CMakeFiles/rnnoise_vst.dir/RnNoiseVstPlugin.cpp.obj
<command-line>:0:0: warning: "__cdecl" redefined
<built-in>: note: this is the location of the previous definition
[ 73%] Linking CXX shared library ..\..\bin\vst\librnnoise_vst.dll
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
src\vst_plugin\CMakeFiles\rnnoise_vst.dir\build.make:155: recipe for target 'bin/vst/librnnoise_vst.dll' failed
Mingw32-make[2]: *** [bin/vst/librnnoise_vst.dll] Error 1
CMakeFiles\Makefile2:251: recipe for target 'src/vst_plugin/CMakeFiles/rnnoise_vst.dir/all' failed
Mingw32-make[1]: *** [src/vst_plugin/CMakeFiles/rnnoise_vst.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
Mingw32-make: *** [all] Error 2

Any help would be appreciated because I don't know anything about how to solve this issue.

**Comment by werman** [comment]
Looks like you are missing `mingw32-pthreads-w32` package. I don't have Windows so I couldn't give you exact direction, you should be able to install it via some mingw gui or via command line.

**Comment by viral98** [comment]
Hey could you share the source of VST2.x plugins? I am stuck with the same issue. Steinberg just provides 3.x now

**Comment by Aktzin03** [comment]
Many thanks werman! Building went correctly this time. The only problem is that it isn't recognized by Cantabile. Oh well, I can figure out how Carla works. I found the vst2 SDK here: https://archive.org/details/VST2SDK. I hope that helps you viral98!
