### ISSUE TITLE
VAD Threshold eventually suppresses completely if set to 1

### ISSUE THREAD

**Issue by Katzenwerfer** [werman/noise-suppression-for-voice#196]
Playing with the parameters of the plugin in Equalizer APO, I found that a threshold of 0.99 and 1.0 work the best.
Although the latter seems to have an issue where it eventually suppresses all audio and stops detecting incoming voice until I lower the value.

**Comment by Trixarian** [comment]
Probably because 1.0 means that 100% of the incoming audio is expected to be vocal audio - which essentially means it's not processing 'noise' since you just told the plugin that there isn't any and it's working like expected

**Comment by giou** [comment]
I wish it had a three-digit decimal place so that I could use a value of 0.995.
0.99 still produces some noise, but never cuts off the voice.
1.0 does eliminate all the noise, but occasionally cuts off the voice.

**Comment by pallaswept** [comment]
There's no issue here, [everything is working as intended, as described by Trixarian ](https://github.com/werman/noise-suppression-for-voice/issues/196#issuecomment-2237063348)

Accordingly, this issue should be closed, to relieve load on the developer. Could you please take care of that for us @Katzenwerfer ?

To assist people posting here:

Consider that we go to a nightclub and there is lots of cheering and music playing, if I talk, even though you are WAY smarter than an AI audio plugin, you still might not be able to understand me. This is like that. If there is enough background noise, it doesn't matter how big your brain is, how smart the AI is, or how many decimal places you get. Sometimes you just need to go somewhere more quiet to talk; sometimes you just need to put the mic in a better place, adjust the gain, fix your cabling, filter out that extremely loud fan, etc, etc.

If you're finding that you have so much noise that you're wishing for more decimal places, the answer isn't the decimal places, it's reducing the noise:
https://en.wikipedia.org/wiki/Garbage_in,_garbage_out

I won't talk too much about *how* to fix your mic- there's lots of advice on the internet about that and it will take some experimentation. I just hope that I have helped to explain *why* you need to fix your mic. 

And yes, I do understand that sometimes, that can be very difficult, especially on a low budget. And I do know that a plugin like this one can be a very useful tool against such difficulties. But, that doesn't man that this plugin is *the* answer to such problems, and if you try to (ab)use it as such, and it does not work, that might not suggest an issue with this plugin ;)

I imagine that if you were absolutely unable to further improve the quality of audio input to this plugin, you might consider re-training the model to suit your specific noisy environment/equipment. There's documentation on that process elsewhere here.

Hope that helps!

**Comment by Katzenwerfer** [comment]
Lately, I've been able to use the plugin with a threshold of 1 without issues. I have to wonder why it works know, but it's good enough for me. I just hope it's not a common enough issue to warrant reopening this at some point.
