### ISSUE TITLE
Linux newbie here, how do I configure the plugin? It seems too agressive and it says I can change this in readme

### ISSUE THREAD

**Issue by A-Random-Lantern** [werman/noise-suppression-for-voice#23]
I don't know how to configure this since I'm new to this part of linux. Any help would be appreciated.

**Comment by werman** [comment]
Hi, what do you mean by "too aggressive"? You could try to set `control=0` in the line which looks like:

```
pacmd load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out 
label=noise_suppressor_mono plugin=/path/to/librnnoise_ladspa.so control=0
```

**Comment by A-Random-Lantern** [comment]
Ah thanks, when I mean too aggressive. It cuts off some of my talking.

**Comment by werman** [comment]
Then try setting `control` to zero and restart pulseaudio

**Comment by werman** [comment]
Also, does it cut mid sentence, or at the end?

**Comment by A-Random-Lantern** [comment]
At the end, it's not a problem that happens always. It could just be me anyways, it's fine.
