### ISSUE TITLE
example of how to use with video conferencing on linux

### ISSUE THREAD

**Issue by spotiris** [werman/noise-suppression-for-voice#26]
Firstly thank you for putting this together, I have tested it with audacity and it works great.
It is very desirable to use this with video conferencing, unfortunately it is difficult to understand how to set it up.
I can not configure this in a way that works with Google Meet; sometimes it works but I cannot hear other people, and sometimes I can hear others but my mic is disabled. Sometimes the mic disappears, sometimes my pulseaudio daemon dies.

A clear example on how to set up pulseaudio and the system defaults would greatly improve the utility of this work.

**Comment by werman** [comment]
I have the same configuration of pulseaudio as in the readme: https://github.com/werman/noise-suppression-for-voice#pulseaudio

What browser do you have? I have no troubles with Google Meet in Firefox, however Chrome/Chromium don't want to see the additional think (it actually could see and use it but not in any real-world webrtc app), I don't know why and I think it's a Chrome's issue.

**Comment by spotiris** [comment]
Thanks for the speedy response.
I am using Chrome. I can confirm that Firefox actually works.
I am using the same config in the README, but I am using my headphones.
By changing the default system playback source to my laptop's speakers, then back to headphones, the LADSPA sink begins working and outputting as expected.
The problem is now that I can hear myself in my headphones... Any ideas?

**Comment by werman** [comment]
> I am using Chrome. I can confirm that Firefox actually works.

Unfortunately I don't know what to do with Chrome, maybe I'll file a bug.  

> but I am using my headphones.

Shouldn't really matter.

> The problem is now that I can hear myself in my headphones... Any ideas?

Something got messed up in how sinks are linked together. You could kill pulseaudio to just reset the config `pulseaudio -k` (sometimes strange things happen to pulseaudio). Or you could look carefully at pavucontrol:

In "Recording" tab "Loopback to LADSPA ..." should be linked to your mic.
In "Output Devices" - "LADSPA Plugin..." and "Null Output" should not be set as fallback.
In "Input Devices" - "Monitor of Null Output" should be set as fallback.

**Comment by spotiris** [comment]
Thanks @werman , I think it is working properly with the fallbacks set properly. 
Please include that info in the README for others, and mention the Chrome issue.
Really great results!
