### ISSUE TITLE
No output of "Monitor of Null Ouput"

### ISSUE THREAD

**Issue by Krulvis** [werman/noise-suppression-for-voice#27]
I've been using this module for a while now and it has always worked perfectly. Since I updated arch yesterday, however, the output of "Monitor of Null Output" remains 0. It is visible in the PulseAudio GUI and I can set it as fallback. But the audio level simply remains 0.

![image](https://user-images.githubusercontent.com/21366036/85394580-1229e200-b54f-11ea-8537-ee134fd8806e.png)

These are the settings files that I use:

```
.include /etc/pulse/default.pa

load-module module-null-sink sink_name=mic_denoised_out
load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_stereo plugin=/opt/ladspa/librnnoise_ladspa.so control=50
load-module module-loopback source=alsa_input.pci-0000_00_1f.3.analog-stereo sink=mic_raw_in channels=2 latency_msec=1

set-default-source mic_denoised_out.monitor

```

[default.pa.txt](https://github.com/werman/noise-suppression-for-voice/files/4818794/default.pa.txt)

I recompiled librnnoise_ladspa.so after I noticed it didn't work anymore (after system update) but to no avail. I checked `pacmd list-sources` and the mic is still named accordingly: `name: <alsa_input.pci-0000_00_1f.3.analog-stereo>`

I added the `latency_msec=1` configuration already before the arch update that broke it since I originally had a long delay.

After I updated arch and noticed it broke I tried the following steps without any success:
 - removing `latency_msec=1`
 - switching to mono rather than stereo `channels=1` & `label=noise_suppressor_mono`

**Comment by werman** [comment]
What pulseaudio version do you have?

I have 13.0-3 and and I don't see it being newer in https://www.archlinux.org/packages/extra/x86_64/pulseaudio/ (however it is flagged out-of-date).

Maybe pulseaudio logs could tell something:
```
sudo killall pulseaudio && pulseaudio --start -vvvvvv --log-meta=true --log-time=true
```

**Comment by Krulvis** [comment]
I also have pulseaudio 13.0-3. Now I am extremely confused :P. I'm currently in a meeting and can't be messing with my sound too much but I'll check with logs in a couple hours. Thanks for the quick response!

**Comment by Krulvis** [comment]
Running the command you provided returns the following:
```
(   0.000|   0.000) D: [pulseaudio][../pulseaudio/src/pulsecore/conf-parser.c:184 pa_config_parse()] Parsing configuration file '/etc/pulse/client.conf'
(   0.000|   0.000) D: [pulseaudio][../pulseaudio/src/pulsecore/conf-parser.c:285 pa_config_parse()] /etc/pulse/client.conf.d does not exist, ignoring.
(   0.003|   0.003) I: [pulseaudio][../pulseaudio/src/daemon/main.c:801 main()] Daemon startup successful.

```
Doesn't seem like there is something going wrong? I have absolutely no idea how to debug this issue...

**Comment by werman** [comment]
Ah, the final piece is:
```
journalctl -b /usr/bin/pulseaudio
```

**Comment by Krulvis** [comment]
```
Jun 23 14:37:13 krulvis-universe pulseaudio[48046]: W: [pulseaudio] module-loopback.c: Configured latency of 5.00 ms is smaller than minimum latency, using minimum instead
Jun 23 14:37:13 krulvis-universe pulseaudio[48046]: W: [pulseaudio] module-loopback.c: Cannot set requested sink latency of 2.25 ms, adjusting to 2.50 ms
Jun 23 14:37:13 krulvis-universe pulseaudio[48046]: W: [pulseaudio] module-loopback.c: Cannot set requested source latency of 2.25 ms, adjusting to 2.50 ms
Jun 23 14:37:13 krulvis-universe pulseaudio[48046]: E: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.bluez.service not found.
Jun 23 14:37:13 krulvis-universe pulseaudio[48046]: W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 12.00 ms
Jun 23 14:37:23 krulvis-universe pulseaudio[48046]: W: [pulseaudio] module-loopback.c: Too many underruns, increasing latency to 17.00 ms

```

**Comment by werman** [comment]
I see nothing wrong in logs. Then most likely something wrong in configuration in pavucontrol...

Looking carefully at volumes and enabled status in pavucontrol  might help. Or looking at `pacmd list-sources`.

Puselaudio configuration is a bit weird.

**Comment by Krulvis** [comment]
When I boost both my mic and "Monitor of Null Output" in pavucontrol to max cap I seem to get some output but the quality is definitely worse and lower quality than before the update. Can't figure anything else out atm, default.pa seems to be fine.

**Comment by werman** [comment]
I don't know what could gone wrong with your configuration, you could post the output of 
```
pacmd list-sources
pacmd list-sinks  
pacmd dump
```
Maybe something would be visible there...

**Comment by Krulvis** [comment]
I have honestly no idea what happened, I didn't change any settings but this morning it all worked fine again. It might have been a problem with my microphone al tough I wouldn't be able to tell you what the exact problem was...

**Comment by Krulvis** [comment]
This issue was never fixed and I just boosted the original input device volume + Monitor of Null Output to the max but am constantly getting complains that I am difficult to hear.
![image](https://user-images.githubusercontent.com/21366036/94063169-010b9e00-fde8-11ea-8349-01ae15ce6f40.png)
^ This is what it looks like when I talk with regular volume in the mic. Built-in Audio Analog Stereo captures it normally but then Monitor of Null Ouput is barely outputting anything...

**Comment by Krulvis** [comment]
I have to re-open this issue. I simply have no idea what the cause is and I have tried many things but I simply get no output from the noise supressed sink (monitor of null output). First I had to boost my mic really loud to get output but now that doesn't even work anymore. If I use the mic directly in Discord for example people can heard me but there's clearly noise coming with my voice.

This is my default.pa:
```
.include /etc/pulse/default.pa

load-module module-null-sink sink_name=mic_denoised_out rate=48000
load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_mono plugin=/home/krulvis/Downloads/noise-suppression-for-voice-master/build-x64/bin/ladspa/librnnoise_ladspa.so control=0
load-module module-loopback source=alsa_input.pci-0000_00_1f.3.analog-stereo sink=mic_raw_in channels=1 source_dont_move=true sink_dont_move=true latency_msec=20

#update-source-proplist mic_denoised_out device.description="Denoised Mic"

load-module module-remap-source source_name=denoised master=mic_denoised_out.monitor channels=1

set-default-source mic_denoised_out.monitor
```

This is my `pactl list sources | grep 'Name:'` output:
```
Name: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2.monitor
Name: alsa_output.usb-Devine_Centro2i2o-01.analog-stereo.monitor
Name: alsa_input.usb-046d_Logitech_Webcam_C930e_B67E42EE-02.analog-stereo
Name: alsa_input.pci-0000_00_1f.3.analog-stereo
Name: mic_denoised_out.monitor
Name: mic_raw_in.monitor
Name: denoised
```

I get the same result if I leave out the module-remap-source line. 

Is there any way to properly debug this?

**Comment by Krulvis** [comment]
Apparently you can just use `set-sink-volume` which solves the problem for me.

**Comment by werman** [comment]
@Krulvis  I could only say that debugging pulseaudio is hard... It's good that you find a solution.
