### ISSUE TITLE
No sound coming from monitor

### ISSUE THREAD

**Issue by aaronjensen** [werman/noise-suppression-for-voice#28]
My `default.pa` looks like this:

```
.include /etc/pulse/default.pa

load-module module-null-sink sink_name=mic_denoised_out
load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_mono plugin=/usr/local/lib/ladspa/librnnoise_ladspa.so control=50
load-module module-loopback source=alsa_input.pci-0000_0f_00.4.analog-stereo sink=mic_raw_in channels=1

set-default-source mic_denoised_out.monitor
```

I can't get that monitor to work in any application. I'm testing with Gnome sound recorder. In pavu control I see the blue bar on the loopback to LADPSA moving in the recording tab, but I don't see blue bars on either the monitor of null output or monitor of ladspa in the input devices tab (should I?)

Any tips for debugging or configuration?

<details>

<summary>pavucontrol setting screenshots</summary>

![Screenshot from 2020-06-25 14-21-28](https://user-images.githubusercontent.com/8588/85796721-45a37280-b6ef-11ea-89e2-d008677417d3.png)
![Screenshot from 2020-06-25 14-21-33](https://user-images.githubusercontent.com/8588/85796722-46d49f80-b6ef-11ea-8819-f607e7615a4e.png)
![Screenshot from 2020-06-25 14-21-37](https://user-images.githubusercontent.com/8588/85796723-46d49f80-b6ef-11ea-8976-614ac49f4b77.png)
![Screenshot from 2020-06-25 14-21-41](https://user-images.githubusercontent.com/8588/85796724-476d3600-b6ef-11ea-860f-dc30b1f7c773.png)
![Screenshot from 2020-06-25 14-21-49](https://user-images.githubusercontent.com/8588/85796725-476d3600-b6ef-11ea-9625-0cd86db90df6.png)

</details>

**Comment by werman** [comment]
On "Recording" tab you seem to have loopback disabled:

![image](https://user-images.githubusercontent.com/3993671/85797395-300c6800-b744-11ea-8d23-e7acd7e72470.png)

**Comment by aaronjensen** [comment]
omg, that was it. Thank you so much. I wonder why it was muted by default. Could the pa config be modified to set that to unmuted by default?

**Comment by werman** [comment]
It shouldn't be muted by default...

**Comment by aaronjensen** [comment]
Very strange. I've got other problems too it seems, rebooting with the `default.pa` above causes my sound output to not work until i restart pulse... I've got some diagnosing to do.

In any case, if it is an option of `load-module`, it wouldn't hurt to set it enabled in there by default.

**Comment by werman** [comment]
You could look at output of the next commands:
```
pacmd list-sources
pacmd list-sinks  
pacmd dump
journalctl -b /usr/bin/pulseaudio
```

I don't see any setting of modules which could cause your issues.

**Comment by aaronjensen** [comment]
The issue appears to be that on boot, my device is not available. It's a headphone jack, so I wonder if it has to detect that there's something plugged into the jack first (there is, but maybe it takes time to do that when the system boots?)

Is there a way to add the loopback in response to that device coming available?

```
-- Logs begin at Fri 2020-06-19 08:42:22 PDT, end at Fri 2020-06-26 21:05:07 PDT. --
Jun 26 21:03:02 pop-os pulseaudio[4019]: No such source.
Jun 26 21:03:02 pop-os pulseaudio[4019]: Failed to load module "module-loopback" (argument: "source=alsa_input.pci-0000_0f_00.4.analog-stereo sink=mic_raw_in channels=2"): initialization failed.
Jun 26 21:04:26 pop-os pulseaudio[4019]: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Jun 26 21:04:26 pop-os pulseaudio[4019]: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
Jun 26 21:04:26 pop-os pulseaudio[4019]: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```

Another problem I've encountered is that if I unplug the headset and plug it back in, it ends up creating a new device and the previously create modules no longer work.

**Comment by aaronjensen** [comment]
Via https://bfccomputing.com/2013/09/05/dynamic-range-compression-for-pulseaudio/

```
set-sink-volume alsa_output.pci-0000_00_14.2.analog-stereo 65536
set-sink-mute alsa_output.pci-0000_00_14.2.analog-stereo 0
```

> The last two lines are optional, but I often find that PulseAudio comes up with with volumes down and the devices muted, so this helps avoid the ‘no sound on startup’ problem.

I wonder if that's what I ran into when I first set it up.

**Comment by aaronjensen** [comment]
I'm going to go ahead and close this out, if someone else runs into this problem, hopefully it'll help.
