### ISSUE TITLE
Celt no longer exists, upgrade to [libopus](https://github.com/xiph/opus)

### ISSUE THREAD

**Issue by Lucretia** [werman/noise-suppression-for-voice#3]

**Comment by werman** [comment]
I fail to see how it is applicable to this library, no codecs are used in rnnoise, there is probably one file from celt but that's all. Or I'm missing something?

**Comment by jagger2048** [comment]
In my comprehension of the rnnoise algorithm, the celt related file is a part of the Linear predictive coding, LPC, processing, in other words, it is a part of the algorithm. Opus also contains this process in the codec. So it is better to keep it as it is from the Rnnoise library.

**Comment by liziru** [comment]
> Celt has been merged into Opus, Celt doesn't exist.

what is the CELT?
