### ISSUE TITLE
Offload to the GPU?

### ISSUE THREAD

**Issue by Two-Tone** [werman/noise-suppression-for-voice#31]
It'd be nice if there was an option to offload the NN to the host GPU, that way it doesn't eat up a good chunk of the user's CPU. It'd need to be done via OpenCL in order to remain hardware agnostic.

**Comment by werman** [comment]
That's out of my league, I'm not a machine learning engineer. Also there was a discussion in the original library repo: https://github.com/xiph/rnnoise/issues/109. Rnnoise is lightweight enough to be comfortably run on the CPU.
