### ISSUE TITLE
Hard crash on Linux while in Zoom call

### ISSUE THREAD

**Issue by aaronjensen** [werman/noise-suppression-for-voice#32]
Hi there,

I've got a new Linux machine and I have twice now hard crashed while in a Zoom call with this plugin enabled. I certainly cannot blame the plugin as I don't really have any detail about the crash (the screen froze completely and would not respond to anything). I'm curious if anyone else has experience this while using this plugin? I'm going to try disabling it for a while and see if that alleviates the issue.

**Comment by werman** [comment]
> the screen froze completely and would not respond to anything

Haven't used it with zoom, but in two years I didn't have any crashes which could be connected to the plugin. You could check `journalctl` and `coredumpctl list` if there is anything about the hang there.

The only hard-freeze this plugin could theoretically cause is out-of-memory, but it should be visible in journalctl.

**Comment by aaronjensen** [comment]
Thanks for the `journalctl` pointer. It's actually my [new video card](https://gitlab.freedesktop.org/drm/amd/-/issues/892). Sigh.
