### ISSUE TITLE
Fedora RPM Package

### ISSUE THREAD

**Issue by lkiesow** [werman/noise-suppression-for-voice#39]
I've started building a Fedora RPM package for this since it's quite useful with the web conferences we all are doing right now. For now, I'll just build a Copr repository (user repository) since I'm building from the git head and have some minor patches applied. Maybe I'll push this towards the main project in the future.

I'll keep you up to date with the current state here. But feel free to close this if you like to not have it show up as open.

Do you want me to contribute Fedora-specific documentation once the repository exists? Or do you want to keep the repository clean of all distribution-specific things?

**Comment by werman** [comment]
> Do you want me to contribute Fedora-specific documentation once the repository exists? Or do you want to keep the repository clean of all distribution-specific things?

Distribution specific docs could be added to the wiki, the readme is already too long =)

**Comment by lkiesow** [comment]
The package repository can be found on [Fedora Copr](https://copr.fedorainfracloud.org/coprs/lkiesow/noise-suppression-for-voice/).
Right now, it just contains the LADSPA plugin.

With that, an installation on Fedora would look like this:

```sh
sudo dnf copr enable -y lkiesow/noise-suppression-for-voice
sudo dnf install -y ladspa-realtime-noise-suppression-plugin
```

Since the plugin will be installed in the default LADSPA plugin location, you can also [go with the recommended way of loading the plugin by just using its name](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-ladspa-sink).

```
pacmd load-module module-null-sink sink_name=mic_denoised_out
pacmd load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_stereo plugin=librnnoise_ladspa control=50
pacmd load-module module-loopback latency_msec=1 source=... sink=mic_raw_in channels=2
```

**Comment by werman** [comment]
Sorry for the delay, done.
