### ISSUE TITLE
Step by step guide to configure in windows

### ISSUE THREAD

**Issue by bssankaran** [werman/noise-suppression-for-voice#49]
This plugin works perfectly for me, and first of all thanks for developing it !

I found it a bit difficult to figure out how to configure this plugin on windows. But I was able to do it in a while, and I wanted to share the steps so that the others need not spend much time.

The below is the article that I wrote.
https://medium.com/@bssankaran/free-and-open-source-software-noise-cancelling-for-working-from-home-edb1b4e9764e?sk=3953dc1e7d414f5084a64c9facd71f98

I am not sure if opening an issue is the right place to express this, but I did not find any other way. Feel free to delete the issue if you feel it is not appropriate or doesnt follow the guidelines.

**Comment by werman** [comment]
Thank you! I'll include it into the readme.

**Comment by bssankaran** [comment]
Thanks, that's great !
