### ISSUE TITLE
(IDEA)  Individual Voice Recognition

### ISSUE THREAD

**Issue by franktntx** [werman/noise-suppression-for-voice#52]
Hi, I have an idea for the plugin, I know it seems crazy, but it would be possible to add speech recognition?. Let me explain, that I only captured a single voice ignoring other voices in the background, would that be possible?

By the way I wanted to thank you for this wonderful plugin, greetings.

**Comment by werman** [comment]
Hi, unfortunately no. It's not me who made a base library - I just packaged it. And the problem of voice detection/separation from noise is much simpler than extracting a specific voice from many.
