### ISSUE TITLE
Compile VST plugin with SDK3, cannot find pluginterfaces/vst2.x/ files?

### ISSUE THREAD

**Issue by Sku4l** [werman/noise-suppression-for-voice#54]
First, I would like to apologize, because I feel like this is a really stupid question, but as VST noob, I have been circling for quite some time and cannot find the information anywhere. 

After failing to understand how to add parameters such as VAD under the VSTHost software on Windows, I decided to compile myself to be able to play with and tweak this parameter.

So my new problem is that I cannot find the "files of the vst2 sdk from pluginterfaces/vst2.x/". I could not find the sdk2, so I downloaded the available sdk from https://www.steinberg.net/vst3sdk. It contains the _VST2_SDK\public.sdk\source\vst2.x_ but I cannot find the appropriate "pluginterfaces" folder.
There is a "pluginterfaces" folder in _\VST3_SDK\pluginterfaces_ but it doesn't seem to match. I tried copying these files for compilation but I get the message:

_CMake Warning at src/vst_plugin/CMakeLists.txt:23 (message):
  pluginterfaces/vst2.x/aeffect.h does not exist._

This seems pretty obvious as I do not have an _affect.h_ file in the folder. So if anyone knows where to find the files, it would be fantastic.

Again, sorry if this question is stupid!

**Comment by werman** [comment]
VST2 sdk isn't available on the official website, you could find it here https://archive.org/details/VST2SDK
