### ISSUE TITLE
obs studio librnnoise vst plugin

### ISSUE THREAD

**Issue by R0tator** [werman/noise-suppression-for-voice#56]
When i use that plugin in obs studio mic filter. the plugin works like charm but my viewers i mean the stream output audio only appears on **left ear not right ear**. how do i fix that? i tried changing from advanced audio properties to tick mark the mono in mic but that do not work when the vst plugin filter is applied. can you help me about it?
![librr](https://user-images.githubusercontent.com/23266509/98523487-2c672100-22a0-11eb-9146-248a49e5bb32.PNG)
![libr](https://user-images.githubusercontent.com/23266509/98523493-2e30e480-22a0-11eb-8297-f7c46de74f3a.PNG)

**Comment by werman** [comment]
That's a bit strange... I think having a stereo vst plugin might help in this case. I'll give you one to test.

**Comment by R0tator** [comment]
> That's a bit strange... I think having a stereo vst plugin might help in this case. I'll give you one to test.

thanks a lot!

**Comment by werman** [comment]
Here are two variants:
* Stereo in -> Stereo out (both channels are processed)
* Mono in -> Stereo out (result is just duplicated)

[librnnoise_vst_test.zip](https://github.com/werman/noise-suppression-for-voice/files/5542703/librnnoise_vst_test.zip)

**Comment by werman** [comment]
There is stereo version in the new release, also there is GUI to change params.
