### ISSUE TITLE
New device listed as an output and super weird sounds coming from output

### ISSUE THREAD

**Issue by umutyazgan** [werman/noise-suppression-for-voice#57]
I followed the guide for Linux step by step, but the new device is listed as an output instead of an input.

[![Screenshot-20201113-235719.png](https://i.postimg.cc/T3mWs6cQ/Screenshot-20201113-235719.png)](https://postimg.cc/TKdwyBFW)

And some weird sounds keep coming from my headphones. Sounds like some kind of static but not exactly, I don't know how to describe it.

This is a laptop and I do not have any external microphones. `pactl list sources short` gave me these devices:
```
0	alsa_output.pci-0000_00_1f.3.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
1	alsa_input.pci-0000_00_1f.3.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
```
I tried them both. `alsa_input.pci-0000_00_1f.3.analog-stereo` gave me those weird sounds and `alsa_output.pci-0000_00_1f.3.analog-stereo.monitor` did not give any weird sounds but it was also listed as an output.

I also checked available input/output devices in OBS. It was also the same there, plugin devices being listed as output.

**Comment by werman** [comment]
>  but the new device is listed as an output instead of an input.

It is intended or rather that's how it works. You should be able to select "Monitor of Null Output" as a recording source.

You indeed need `alsa_input`, you could confirm that it is a mic by looking at `pactl list sources`.

> And some weird sounds keep coming from my headphones. Sounds like some kind of static but not exactly, I don't know how to describe it.

Hmmm

So, are you able to select  "Monitor of Null Output" as a source of recording for apps? Does it work?

**Comment by umutyazgan** [comment]
Unfortunately, no. In OBS Studio, only option for the Mic/Auxiliary Audio is "Built-in Audio Analog Stereo".

**Comment by werman** [comment]
Some apps do not play nice with the default configuration, you may want to try the workaround for chromium.

**Comment by werman** [comment]
You also could check in Audacity.

**Comment by umutyazgan** [comment]
I did the Chromium workaround and now I am able to select "Remapped Monitor of Null Output" in OBS Studio as a mic device. Thank you. Now it works, but the voice quality did not improve at all. I probably need a better mic.

**Comment by werman** [comment]
Yes. if your issue is in the quality of the sound - this plugin won't help. It helps with filtering out non-voice sounds, not with denoising voice itself.
