### ISSUE TITLE
Plugin affecting Output

### ISSUE THREAD

**Issue by Sithic** [werman/noise-suppression-for-voice#58]
Excuse my ignorance, I have never used any programs like EqualizerAPO before and I have no idea if it is just a simple setting or a bug. I am using this plugin because Discord suppression is trash and yours hides my mouse clicks really well. 
How would I fix the plugin working on my output as well? I went to YouTube and the audio was sounding choppy and I unchecked the plugin to get it back to normal. What would I need to do for the plugin to only effect my input like my microphone?

Thanks in advance for any help.

**Comment by werman** [comment]
Hi, have you followed this guide from the readme https://medium.com/@bssankaran/free-and-open-source-software-noise-cancelling-for-working-from-home-edb1b4e9764e ?

**Comment by werman** [comment]
There is a paragraph starting with:
> There is a caveat here, that the noise cancellation plugin that we are going to configure in the below steps will be applied to all the devices that we select in this step by default...

That's what you need.

**Comment by Sithic** [comment]
That worked! I read it.. but I skimmed it. Thanks a ton for quick reply too!
