### ISSUE TITLE
specifying rate=48000 causes intermittent pauses

### ISSUE THREAD

**Issue by christf** [werman/noise-suppression-for-voice#60]
when specifying the rate to 48khz (my microphones have either 16 or 44.1khz but not 48, I get intermittent pauses that sound like they are artefacts from resampling.

When leaving out the parameter sound seems fine.
According the commit this parameter was introduced to obtain more stability in the detection. It seems something unexpected is happening with the samplerate causing artifacts, as if there was too little data passed to the audio system which compensates by placing intermittent pauses....

**Comment by werman** [comment]
The rnnoise was trained on 48 as far as I can remember but actually works completely fine on 44.1. I don't think that the issue you encountered originated in this plugin. So. if it works without resampling - just let it be.

**Comment by christf** [comment]
the parameter seems to do something different than expected: there is no resampling going on. it will just treat the data as 48khz which explains the gaps in the audio.

I really think this is a documentation issue that should be fixed. If resampling to 48khz yields better results, resampling should be included.
