### ISSUE TITLE
How would I train the model with additional noise profiles?

### ISSUE THREAD

**Issue by peteygao** [werman/noise-suppression-for-voice#63]
The existing model doesn't work well with "non-stationary" noises (knocks, bubbles, etc). It's great for stationary noise removal (fan noise, engine noise, persistent static in the mic, etc.).

I've collected a bunch of audio samples of noise I want to train and improve the model with, but I have no idea where to begin with regards to the training process itself. Just need a pointer to the right place to start!

Thanks!

**Comment by werman** [comment]
You should probably look at https://github.com/xiph/rnnoise/issues/109

**Comment by RXAldreezee** [comment]
Check this repo for the training.
https://github.com/Desklop/RNNoise_Wrapper
