### ISSUE TITLE
What files do I put in the VST folders?

### ISSUE THREAD

**Issue by UHDbits** [werman/noise-suppression-for-voice#64]
I can't get the LV2 version working, but I don't know what to put in the the VST folders. Can anyone help?

**Comment by werman** [comment]
Hi, what do you want to achieve? What's your system, application you are using and the goal?

**Comment by UHDBits** [comment]
> Hi, what do you want to achieve? What's your system, application you are using and the goal?

I'm trying to build the VST (2 or 3?) plug-in. macOS High Sierra, Audacity (I can use something else free if needed) and I'm just trying to cancel audio from my voice clips.

**Comment by werman** [comment]
You could find VST2 sdk at https://archive.org/details/VST2SDK (`vst_sdk2_4_rev2.zip`) and copy files from `%sdk_dir%/pluginterfaces/vst2.x/` to `src/pluginterfaces/vst2.x/` and from `%sdk_dir%/public.sdk/source/vst2.x/` to `src/vst2.x/`
