### ISSUE TITLE
VST2 plugin: can't save VAD threshold in Cantabile

### ISSUE THREAD

**Issue by jvdeijnden** [werman/noise-suppression-for-voice#67]
I use Cantabile as VST host and have to manually set the VAD Threshold every time Cantabile is restarted. VST presets don't work, but I can import/export the program with saved VAD (manually).

I'm not sure if this is an issue with the plugin itself or Cantabile.

**Comment by goodfore** [comment]
I have the same problem. I use "VSTHost" as VST host. https://www.hermannseib.com/english/vsthost.htm

Other plugin's parameter saved fine. Although my other plugin is a VST3 plugin, not sure if that makes a difference.

**Comment by Uronic** [comment]
I have the same issue as well.

**Comment by werman** [comment]
Hmmm, it's a bit strange. Looking at the VST sdk I see two ways of how plugin parameters could be saved:

- Plugin doesn't advertise that it support "chunks" - then host just save the parameters 
- Plugin does advertise "chunks" support - host asks plugin to save parameters into a blob which could be later passed back to restore params.

This plugin doesn't support the second option at the moment, it seems some host unconditionally expect it...

**Comment by Arakula** [comment]
You might want to make your PlugIn report that it has 1 program (instead of 0). Confronted with "This PlugIn has no programs", the host won't ask it for any parameter when trying to save the current bank.

**Comment by jukofyork** [comment]
I had this problem too but managed to find a hack fix that works for VSTHost:

Setup a midi source using the "timer" setting and you can them set the parameter on reload (and every 50ms too!).

**Comment by werman** [comment]
@jukofyork I'm preparing new release in develop branch (https://github.com/werman/noise-suppression-for-voice/commits/develop), I think now it support saving parameters since now I'm using JUCE, here are latest build: https://github.com/werman/noise-suppression-for-voice/actions/runs/2618374807. If you could test it - it would be great!

**Comment by jukofyork** [comment]
Hi, thanks I'll try this later today if I get chance. Juk

8 Jul 2022 10:15:34 pm Danil ***@***.***>:

**Comment by jukofyork** [comment]
Hi,

The link the the build you send had expired so I had to use the build from today.

Sadly VSTHost just silently refused to load the either of the plugins. I've no idea why but did notice the file size was much larger than the original dll.

If you have any ideas I can give them a try?

Juk

8 Jul 2022 10:15:34 pm Danil ***@***.***>:

**Comment by Arakula** [comment]
Hmmm, the version from https://github.com/werman/noise-suppression-for-voice/actions/runs/2650728052 could be loaded into VSTHost. At least into my current beta version from https://www.hermannseib.com/programs/beta ...
The Editor screen acts totally weird, however.
![grafik](https://user-images.githubusercontent.com/1124609/178336700-10bdea7b-53ca-4a77-b18b-7da536b0dfcd.png)

**Comment by werman** [comment]
> I've no idea why but did notice the file size was much larger than the original dll.

I now use JUCE framework and there is also GUI, so the size ballooned.

> Sadly VSTHost just silently refused to load the either of the plugins. 

> The Editor screen acts totally weird, however.

Ok, it seems I won't get away without installing Windows into virtual machine and actually testing it...

Thanks!

**Comment by werman** [comment]
> Sadly VSTHost just silently refused to load the either of the plugins

@jukofyork  Could it be that your VSTHost is 32 bit? Because I'm building only x64 version of the plugin.

**Comment by werman** [comment]
@Arakula How did you load it? I installed the beta version, opened it in default configurations, pressed "New Plugin" and selected vst3 dll. Nothing happened afterwards.

**Comment by Arakula** [comment]
Downloaded win_mnoise.zip, opened it, extracted the files from the vst subfolder into a plugin directory, opened VSTHost (latest 1.58 64bit beta, on a 64bit Windows 10), dragged the files onto VSTHost's client area. But it works with "New Plugin" as well. I can't see any "vst3 dll", however. What's that supposed to be?

**Comment by werman** [comment]
@Arakula  Hmmm, after I manually started `VSTHostBridge64` before launching `vsthost` - it now works... Or maybe it's something else, anyway it works now, and without any GUI glitches.

> I can't see any "vst3 dll", however. What's that supposed to be?

I meant `rnnoise.vst3` - it's just a `.dll` but has different extension.

**Comment by werman** [comment]
Back to the original issue, in Cantabile the plugin settings are still not being saved.

**Comment by werman** [comment]
Released v1.01, settings should be saved now. Regarding GUI corruption - I cannot reproduce it, though I updates JUCE and there were a few fixes regarding gui components which might have fixed the corruption. @Arakula  If it is still reproducible please open a new issue.
