### ISSUE TITLE
General-Purpose LADSPA?

### ISSUE THREAD

**Issue by AaronD-GH** [werman/noise-suppression-for-voice#71]
I'm having some difficulty using the LADSPA version as a standalone plugin for a DAW on Lubuntu 20.04.  It seems to compile and install okay, and it appears in the standard directory (/usr/local/lib/ladspa), but it doesn't appear in the DAW's available plugins like all the others do.

Am I just missing something?  Or is there actually a bug somewhere, that prevents it from being detected like the others are?

Terminal dump:

```
aaron@aaron-M6800:~/Downloads/noise-suppression-for-voice-master$ cmake -Bbuild-x64 -H. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at src/vst_plugin/CMakeLists.txt:23 (message):
  pluginterfaces/vst2.x/aeffect.h does not exist.

   Please see vst2.x/FILES.txt and pluginterfaces/vst2.x/FILES.txt


-- Configuring done
-- Generating done
-- Build files have been written to: /home/aaron/Downloads/noise-suppression-for-voice-master/build-x64
aaron@aaron-M6800:~/Downloads/noise-suppression-for-voice-master$ cd build-x64/
aaron@aaron-M6800:~/Downloads/noise-suppression-for-voice-master/build-x64$ make
Scanning dependencies of target RnNoise
[  7%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/celt_lpc.c.o
[ 14%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/denoise.c.o
[ 21%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/kiss_fft.c.o
[ 28%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/pitch.c.o
[ 35%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/rnn.c.o
[ 42%] Building C object src/rnnoise/CMakeFiles/RnNoise.dir/src/rnn_data.c.o
[ 50%] Linking C static library ../../lib/libRnNoise.a
[ 50%] Built target RnNoise
Scanning dependencies of target RnNoisePluginCommon
[ 57%] Building CXX object src/common/CMakeFiles/RnNoisePluginCommon.dir/src/RnNoiseCommonPlugin.cpp.o
[ 64%] Linking CXX static library ../../lib/libRnNoisePluginCommon.a
[ 64%] Built target RnNoisePluginCommon
Scanning dependencies of target rnnoise_lv2
[ 71%] Building CXX object src/lv2_plugin/CMakeFiles/rnnoise_lv2.dir/RnNoiseLv2Plugin.cpp.o
[ 78%] Building CXX object src/lv2_plugin/CMakeFiles/rnnoise_lv2.dir/RnNoiseLv2Lib.cpp.o
[ 85%] Linking CXX shared library ../../bin/rnnoise.lv2/rnnoise_lv2.so
[ 85%] Built target rnnoise_lv2
Scanning dependencies of target rnnoise_ladspa
[ 92%] Building CXX object src/ladspa_plugin/CMakeFiles/rnnoise_ladspa.dir/RnNoiseLadspaPlugin.cpp.o
[100%] Linking CXX shared library ../../bin/ladspa/librnnoise_ladspa.so
[100%] Built target rnnoise_ladspa
aaron@aaron-M6800:~/Downloads/noise-suppression-for-voice-master/build-x64$ sudo make install
[sudo] password for aaron: 
[ 50%] Built target RnNoise
[ 64%] Built target RnNoisePluginCommon
[ 85%] Built target rnnoise_lv2
[100%] Built target rnnoise_ladspa
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/lv2/rnnoise.lv2/rnnoise_lv2.so
-- Up-to-date: /usr/local/lib/lv2/rnnoise.lv2
-- Installing: /usr/local/lib/lv2/rnnoise.lv2/rnnoise.ttl
-- Installing: /usr/local/lib/lv2/rnnoise.lv2/manifest.ttl
-- Installing: /usr/local/lib/ladspa/librnnoise_ladspa.so
aaron@aaron-M6800:~/Downloads/noise-suppression-for-voice-master/build-x64$ 
```
![00_Troubleshooting_Screenshot](https://user-images.githubusercontent.com/76844290/108790532-93a09c80-7542-11eb-9150-9c8319bc4407.png)

**Comment by JohnPeel** [comment]
I know at least in Carla, I have to rescan the plugins for new ones to come up in the list. Not sure about "Non Mixer", but you might find a similar option.

**Comment by AaronD-GH** [comment]
No option for that here.  It seems to be automatic on startup.  The others simply appeared on their own after `make install`ing them and restarting the DAW.

I see that the names in the list are not necessarily the filenames.  Is it called something weird, perhaps, that I haven't thought to search for?  Or maybe that field isn't filled at all for this one and so there's nothing to show it with?  Mostly grasping at straws here.

![00_Troubleshooting_Screenshot2](https://user-images.githubusercontent.com/76844290/110214173-0bd36000-7e69-11eb-922e-ac01f1b8a45c.png)

**Comment by JohnPeel** [comment]
Here is what I get in Carla.

![image](https://user-images.githubusercontent.com/414664/110338966-9fd23280-7ff5-11eb-8c6a-2791782131dc.png)

**Comment by AaronD-GH** [comment]
Hmm...  Okay, so *something* sees it.  It also prompted me to try Audacity, since I already had it installed.  (don't know why I didn't think of that to start with)  That sees it too.  Good test of the plugin itself, but I need to process things live in real time, and Audacity was never designed to do that and still doesn't.

Installed Ardour for another test.  (sudo apt install ardour)  It goes all the way through the initial setup, then can't create a project.  The error message that it gives is completely useless.  So much for that.

Hey, wait a minute!  Why not try Carla?!  The specific one that you say works.  (sudo apt install carla)  Yep!  It does for me too, and some fiddling with the detection requirements got me all of the others that I need too.  So I guess I'll rebuild my project in there.  Thanks for getting me going again!

I'm still curious though, why the specific combination of Non and this plugin doesn't work.  Non sees other plugins, and this plugin works with other hosts.  Why does that specific combination not work?  Much lower priority now, as my roadblock no longer exists, just lingering curiosity.

**Comment by werman** [comment]
Before new release I tested the plugin in a few hosts - it was visible everywhere. Please open a new issue if there are still troubles.
