### ISSUE TITLE
Feature Request: Support other sample rates.

### ISSUE THREAD

**Issue by gnif** [werman/noise-suppression-for-voice#8]
I have already implemented this but I won't make it a PR as my coding style is very different from yours. Currently it's hard coded to support 192KHz and will need some work to get it to build on other platforms.

https://github.com/gnif/noise-suppression-for-voice/commit/0a5e9070b8f7c66107508dc7431481281b86e84f

**Comment by werman** [comment]
That looks like a good idea. I don't think your style is not suitable I just did all in the most simplest way =)
So please, make a pull request and allow me to change it. I'll verify correctness and do some small style changes later.

**Comment by gnif** [comment]
Will do, there are some issues with it I am fixing at the moment, once ready I will issue a PR

**Comment by gnif** [comment]
Please see PR #9
