### ISSUE TITLE
How to check the latency?

### ISSUE THREAD

**Issue by RXAldreezee** [werman/noise-suppression-for-voice#82]
Hi, I have managed to run this on a Raspberry Pi. I want ro know how to check the latency introduced by the plugin? And also how can I lower it. Thank you.

**Comment by werman** [comment]
If you are using pulseaudio you could run `pacmd list-sink-inputs` and find "Latency:" field, as for how to reduce it if it's really big see https://github.com/werman/noise-suppression-for-voice/issues/18

**Comment by RXAldreezee** [comment]
3 sink input(s) available.
    index: 0
        driver: <module-ladspa-sink.c>
        flags: START_CORKED 
        state: RUNNING
        sink: 3 <mic_denoised_out>
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 0.00 ms
        requested latency: 50.02 ms
        sample spec: float32le 2ch 48000Hz
        channel map: front-left,front-right
                     Stereo
        resample method: copy
        module: 27
        properties:
                media.name = "LADSPA Stream"
                media.role = "filter"
                module-stream-restore.id = "sink-input-by-media-role:filter"
    index: 1
        driver: <module-loopback.c>
        flags: VARIABLE_RATE DONT_MOVE START_CORKED 
        state: RUNNING
        sink: 4 <mic_raw_in>
        volume: mono: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 175.05 ms
        requested latency: 50.02 ms
        sample spec: s16le 1ch 44089Hz
        channel map: mono
                     Mono
        resample method: speex-float-1
        module: 28
        properties:
                media.role = "abstract"
                module-stream-restore.id = "sink-input-by-media-role:abstract"
                media.name = "Loopback from USB PnP Sound Device Mono"
                media.icon_name = "audio-card-usb"
    index: 3
        driver: <protocol-native.c>
        flags: START_CORKED 
        state: RUNNING
        sink: 0 <alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-stereo>
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        muted: no
        current latency: 107.41 ms
        requested latency: 99.95 ms
        sample spec: float32le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        resample method: copy
        module: 13
        client: 4 <Firefox>
        properties:
                media.name = "AudioCallbackDriver"
                application.name = "Firefox"
                native-protocol.peer = "UNIX socket client"
                native-protocol.version = "34"
                application.process.id = "1035"
                application.process.user = "pi"
                application.process.host = "pi"
                application.process.binary = "firefox"
                application.language = "en_PH.UTF-8"
                window.x11.display = ":0"
                application.process.machine_id = "75a9c41353b9478e8aa2db15a42d509e"
                application.process.session_id = "2"
                application.icon_name = "firefox"
                module-stream-restore.id = "sink-input-by-application-name:Firefox"

**Comment by RXAldreezee** [comment]
Hi, here are my results, I have set latency_msec=200 since my hardware latency was about 150-160ms.

**Comment by werman** [comment]
Should be good enough for most use cases.

**Comment by RXAldreezee** [comment]
Ok, which one was the latency 175.05 ms or 107.41 ms ?

**Comment by werman** [comment]
I guess that 175 since it's the last in the chain.

**Comment by RXAldreezee** [comment]
Ok, thanks!
