### ISSUE TITLE
Glitchy sound when using suggested module-remap-source (Pulseaudio)

### ISSUE THREAD

**Issue by andyrichardson** [werman/noise-suppression-for-voice#83]
Hey there - first off, thanks for the awesome project! I'm not sure if this issue is specific to this project but I'm kinda at a loss as to where else to look (and maybe others are experiencing this also).

## About

When using the suggested `module-remap-source` pulseaudio module for chrome support, input (and monitoring) become distorted/robotic/glitchy.

## Reproduction

Here is how I'm currently loading the modules.

```
pacmd load-module module-loopback
pacmd load-module module-null-sink sink_name=mic_denoised_out rate=48000
pacmd load-module module-ladspa-sink sink_name=mic_raw_in sink_master=mic_denoised_out label=noise_suppressor_stereo plugin=/nix/store/jq0a66vd86w6zibxc334930nljkbd1av-noise-suppression-for-voice-1.1.0/lib/ladspa/librnnoise_ladspa.so control=90
pacmd load-module module-loopback source=alsa_input.pci-0000_00_1f.3.analog-stereo sink=mic_raw_in channels=2 source_dont_move=true sink_dont_move=true
pacmd load-module module-remap-source master=mic_denoised_out.monitor rate=48000 channels=2
pacmd set-default-source mic_denoised_out.monitor
```

Following those commands, I can hear the noise-suppressed input via the output device working correctly.

Once I open a site in chrome which tries to access the mic input, the audio suddenly becomes stuttery and broken (not just in chrome, but also the monitored audio).

## Additional info

 - I've tried following pulseaudio [troubleshooting steps](https://wiki.archlinux.org/title/PulseAudio/Troubleshooting) (tsched, use_ucm, etc)

**Comment by werman** [comment]
Unfortunately I cannot help with it, this plugin shouldn't produce such sound, most likely it's some kind of pulseaudio issue, and to be honest, I don't know much about pulseaudio, thus I have no ability to help.

**Comment by andyrichardson** [comment]
No worries at all - strangely enough, when switching to [PulseEffects](https://github.com/wwmm/pulseeffects) which also uses RRNoise, I didn't have this problem. 

That being said, I suspect it's something related to pulseaudio config that I was/wasn't doing.

Thanks for the response and keep up the great work :+1:
