### ISSUE TITLE
Package Name in AUR has Changed

### ISSUE THREAD

**Issue by MattByName** [werman/noise-suppression-for-voice#84]
Hi!
Really a minor thing, I tried to change it myself but it wasn't possible to edit the wiki.

You can install librnnoise-ladspa from AUR. The [Arch installation instructions](https://github.com/werman/noise-suppression-for-voice/wiki/Installation---Linux#arch-linux) should be changed to reflect the new AUR name
> You can install [```librnnoise-ladspa```](https://aur.archlinux.org/packages/librnnoise-ladspa/) from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository).
Should now read:
> You can install [```noise-suppression-for-voice```](https://aur.archlinux.org/packages/noise-suppression-for-voice) from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository).

**Comment by werman** [comment]
Done, thanks.
