### ISSUE TITLE
VST plugin crashes when trying to open settings panel on equilizer APO

### ISSUE THREAD

**Issue by deama** [werman/noise-suppression-for-voice#87]
When I load the VST on equilizer APO, it works, but I can't adjust any of the settings because when I try and open the settings panel, it crashes equlizer APO. I tried using another platform but instead the settings panel doesn't work at all, gives me a broken window.

**Comment by werman** [comment]
Duplicate, see https://github.com/werman/noise-suppression-for-voice/issues/44 for workaround. We don't have support GUI settings, the host application may implement its own settings window or not.
