### ISSUE TITLE
VST3 Support

### ISSUE THREAD

**Issue by DailySage** [werman/noise-suppression-for-voice#91]
Hey there i am pretty new with all of this but i am using the Wave Link (Beta with VST support) but it only supports VST3 Plugins.

Would it be possible to get a VST3 version?

**Comment by kuyazee** [comment]
Are there any headways for this?

I've been exploring for days and can't seem to compile a .vst or a .vst3 file for MacOS :(

**Comment by werman** [comment]
Released v1.01, VST3 is now supported.
