### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by MabaKalox** [werman/noise-suppression-for-voice#92]
Sytem - Arch Linux
I have cm106 usb sound card, and when trying to use microphone connected to it with this plugin and pipewire(mic without lugin works, plugin with other micro works), it cause core dumped with following 
<details open>
<summary>error</summary>
<br>
<pre>/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: abort (core dumped)  PIPEWIRE_DEBUG=2 pipewire -c</pre>
</details>

<details open>
<summary>journalctl</summary>
<br>
<pre>Oct 11 20:30:05 mk-arch systemd-coredump[39173]: [🡕] Process 39168 (pipewire) of user 1000 dumped core.
                                                 
Found module linux-vdso.so.1 with build-id: 1b7cecdad90631a6c47a59e5f4f30972fa444cc3
Found module libspa-audiomixer.so with build-id: 36778b3331d303820e46d6cb3e249a0d1417a609
Found module libspa-audioconvert.so with build-id: 4e1b65c5891416dc451204e7648cdf65c028b36a
Found module libgcc_s.so.1 with build-id: 7f8508bb914546ada778809b64b99d234337d835
Found module libstdc++.so.6 with build-id: 8ab0e57054dd1dcba681f217016afc6a4e639783
Found module librnnoise_ladspa.so with build-id: e85b7c1ce5843eb376b60d0379464dd7dd96a88f
Found module libogg.so.0 with build-id: ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
Found module libvorbis.so.0 with build-id: ad0a6c1af8f219b4e314090b6e8847223d424cbe
Found module libopus.so.0 with build-id: 649d3ddab8764d7caf73648004a35cb13e23a5e1
Found module libFLAC.so.8 with build-id: e568dc3d434723c72d6d302eb0b2559f27e91faa
Found module libvorbisenc.so.2 with build-id: 28ed815b8b1d322e6bf2bfdce4b0af2789b74335
Found module libsndfile.so.1 with build-id: 72d5531e74ed3e9afe49e95e449c40cb8984a258
Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
Found module libpipewire-module-filter-chain.so with build-id: 5ecd4fdfe361830b09942ad7bff98e96e140cbca
Found module libpipewire-module-adapter.so with build-id: f690f9db426e1aaf769047087b17891ef8422832
Found module libpipewire-module-client-node.so with build-id: 534b800fc282b8c13a1d7ee8416447f767a21498
Found module libpipewire-module-protocol-native.so with build-id: 9e4632943505580107fda6c14cb6b491ef9cd9da
Found module libpipewire-module-rtkit.so with build-id: aa79836403d7e40cf645a573c9c11fb743b95ee5
Found module libnss_files.so.2 with build-id: 1a36dfc01d3a1010b2ee79766a24a8090a3266d5
Found module libdbus-1.so.3 with build-id: 74f2ab9c60512f3a93c932c3f627564d42e0b11e
Found module libspa-dbus.so with build-id: 879c070e8997cc3eebac4bdf926920dc2dc24eea
Found module libgpg-error.so.0 with build-id: ba85170c2d9343ea05eea8fa2048c212ff4ef552
Found module libgcrypt.so.20 with build-id: db45f5d5e0f7af1e77324fea1885f974619ad268
Found module libcap.so.2 with build-id: c1674f9082fedd415876b9f7d9712269163259b5
Found module liblz4.so.1 with build-id: e63600ab23b2f6997f42fac2fa56e1f02ce159a1
Found module libzstd.so.1 with build-id: 4b10444c1560ebc574af4d5f488b7408b22d450e
Found module liblzma.so.5 with build-id: 8b615460aa230708c5183f16bede67aa0437d95e
Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
Found module libsystemd.so.0 with build-id: f776aaa16b4e2ba7056d01d928e4b2726ffe2b8b
Found module libspa-journal.so with build-id: 43625cd7ba3fa1c7fdbb1cf1fb3dff1d2733b30e
Found module libspa-support.so with build-id: 72a9a0bd243c4bd7d7e00ed76cfe12979ca177ce
Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
Found module libpipewire-0.3.so.0 with build-id: dc97b36efe993325533f45b7e400e14530ad981b
Found module pipewire with build-id:0d0743384e238389dbf2ffe78d7499954de976d3
Stack trace of thread 39170:
#0  0x00007fae3b1a1d22 raise (libc.so.6 + 0x3cd22)
#1  0x00007fae3b18b862 abort (libc.so.6 + 0x26862)
#2  0x00007fae3a59d0f5 _ZN19RnNoiseCommonPlugin7processEPKfPfif (librnnoise_ladspa.so + 0x40f5)
#3  0x00007fae3a59c2d6 _ZN6ladspa7builderI13RnNoiseStereoE4_runEPvm (librnnoise_ladspa.so + 0x32d6)
#4  0x00007fae3a91cb31 n/a (libpipewire-module-filter-chain.so + 0x4b31)
#5  0x00007fae3b3d235c n/a (libpipewire-0.3.so.0 + 0x8035c)
#6  0x00007fae3a2bfd3a n/a (libspa-audioconvert.so + 0x1dd3a)
#7  0x00007fae3b3aef11 n/a (libpipewire-0.3.so.0 + 0x5cf11)
#8  0x00007fae3b3b1ea8 n/a (libpipewire-0.3.so.0 + 0x5fea8)
#9  0x00007fae3b439e8b n/a (libspa-support.so + 0x9e8b)
#10 0x00007fae3b3958bd n/a (libpipewire-0.3.so.0 + 0x438bd)
#11 0x00007fae3b33a259 start_thread (libpthread.so.0 + 0x9259)
#12 0x00007fae3b2635e3 __clone (libc.so.6 + 0xfe5e3)

Stack trace of thread 39168:
#0  0x00007fae3b34379c read (libpthread.so.0 + 0x1279c)
#1  0x00007fae3b442d94 n/a (libspa-support.so + 0x12d94)
#2  0x00007fae3b43accc n/a (libspa-support.so + 0xaccc)
#3  0x00007fae3b3b44b1 n/a (libpipewire-0.3.so.0 + 0x624b1)
#4  0x00007fae3b3d8125 n/a (libpipewire-0.3.so.0 + 0x86125)
#5  0x00007fae3b435ac6 n/a (libspa-support.so + 0x5ac6)
#6  0x00007fae3b439e8b n/a (libspa-support.so + 0x9e8b)
#7  0x00007fae3b3a6160 pw_main_loop_run (libpipewire-0.3.so.0 + 0x54160)
#8  0x00005606f70e62d2 n/a (pipewire + 0x12d2)
#9  0x00007fae3b18cb25 __libc_start_main (libc.so.6 + 0x27b25)
#10 0x00005606f70e648e n/a (pipewire + 0x148e)
Oct 11 20:30:05 mk-arch systemd[1]: systemd-coredump@12-39171-0.service: Deactivated successfully.</pre>
</details>

<details open>
<summary>filter-chain.conf</summary>
<br>
<pre># Noise canceling source
#
# start with pipewire -c filter-chain/source-rnnoise.conf
#
context.properties = {
    log.level        = 0
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    {   name = libpipewire-module-rtkit
        args = {
            #nice.level   = -11
            #rt.prio      = 88
            #rt.time.soft = 200000
            #rt.time.hard = 200000
        }
        flags = [ ifexists nofail ]
    }
    {   name = libpipewire-module-protocol-native }
    {   name = libpipewire-module-client-node }
    {   name = libpipewire-module-adapter }

    {   name = libpipewire-module-filter-chain
        args = {
            node.name =  "rnnoise_source"
            node.description =  "Noise Canceling source"
            media.name =  "Noise Canceling source"
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                        label = noise_suppressor_stereo
                        control = {
                            "VAD Threshold (%)" 50.0
                        }
                    }
                ]
            }
            capture.props = {
                node.passive = true
            }
            playback.props = {
                media.class = Audio/Source
            }
        }
    }
]</pre>
</details>

**Comment by werman** [comment]
There was one fix for a crash which could be similar to yours: https://github.com/werman/noise-suppression-for-voice/commit/89496c24cbc7d8660609f9add5560bf33d78b737 (fixed issue https://github.com/werman/noise-suppression-for-voice/issues/79)

Looking at aur I see that the package uses tagged releases and last release was quite a while ago, I probably should make a new one...
